sharrlotte/MindustryToolNext

- app/[locale]/(user)/logic/page.tsx
> resolve #456

- app/[locale]/(main)/image-generator/router/page.tsx
- app/api/v1/image-generator/route.ts
- tsconfig.json
Add support for splitting the generated image into multiple schematics both vertically and horizontally. Enhance the UI to display image dimensions, split controls, and download functionality. This allows users to manage larger images more effectively and provides better feedback during the generation process.
> feat(image-generator): add split functionality and UI enhancements

- app/[locale]/(main)/admin/(dashboard)/page.tsx
Integrate an iframe to display analytics from an external source, providing real-time monitoring capabilities on the admin dashboard.
> feat(admin/dashboard): add analytics iframe for monitoring

- app/[locale]/(main)/servers/[id]/(dashboard)/player-card.tsx
- app/[locale]/(main)/servers/[id]/logs/server-login-log-card.tsx
- app/globals.css
- components/server/ban-button.tsx
- components/ui/button.tsx
- Update `--destructive` color to improve visibility
- Add `ghost` variant to `EllipsisButton` in server login log card
- Enhance `BanButton` with `DialogTitle` for better accessibility
- Use `asChild` prop in `ContextMenuItem` for consistent button behavior
> refactor(ui): adjust destructive color and improve button consistency

- .prettierrc
- app/[locale]/logic/instruction.node.tsx
- app/[locale]/logic/logic-editor.context.tsx
- app/[locale]/logic/no-file-open-screen.tsx
- app/[locale]/logic/node.tsx
- i18n/server.ts
Restructured the logic editor components to enhance readability and maintainability. Changes include splitting large components into smaller ones, improving variable handling, and refining UI elements. Adjusted Prettier configuration to reduce print width for better code formatting.
> refactor(logic-editor): improve code readability and maintainability

- i18n/server.ts
The unstable_cache function was removed and replaced with a fetch call to handle translations. This change improves the reliability and consistency of the translation fetching mechanism by leveraging the standard fetch API with revalidation and tagging options.
> refactor(i18n): replace unstable_cache with fetch for translations

- app/[locale]/(main)/admin/setting/image/page.tsx
- app/[locale]/docs/[...path]/layout.tsx
- app/[locale]/docs/[...path]/page.tsx
- app/[locale]/docs/doc-type.ts
Introduce a dialog to show the progress of file uploads, improving user feedback during the upload process. The dialog automatically closes when all uploads are completed.
> feat(upload): add dialog for file upload progress display

- app/[locale]/docs/[...path]/layout.tsx
- app/[locale]/logic/error.tsx
- app/[locale]/logic/instruction.node.tsx
- app/[locale]/logic/logic-editor.context.tsx
- app/[locale]/logic/node.tsx
- app/[locale]/logic/page.tsx
- app/[locale]/logic/plus.panel.tsx
- app/[locale]/logic/search.panel.tsx
- app/[locale]/logic/sidebar.tsx
- app/[locale]/logic/toolbar.tsx
- hooks/use-code.ts
- hooks/use-query-state.ts
- query/config/config.ts
The `w-full` class was added to the link's className to ensure it occupies the full width of its container, improving the responsiveness and visual consistency of the NavBarDoc component.
> style(layout): adjust NavBarDoc link width for better responsiveness

- app/[locale]/logic/search.panel.tsx
Improve the search panel by adding detailed match information for each node, including label, category, and item values. This change provides better visibility into search results and highlights the matched text within the results.
> feat(search.panel): enhance search functionality with detailed matches

- app/[locale]/(main)/servers/[id]/(dashboard)/player-card.tsx
- components/server/ban.button.tsx
- components/server/kick.button.tsx
- Refactored kick and ban button components to use useQueryClient for cache invalidation
- Updated command messages to remove leading slashes for consistency
- Converted PlayersCard to a client component and replaced serverApi with useSuspenseQuery
- Replaced ErrorScreen with ErrorMessage for better error handling
> refactor(server): improve player management and error handling

- app/[locale]/(main)/admin/setting/image/page.tsx
- hooks/use-client.tsx
- instrumentation.ts
- next.config.ts
Refactor the Sentry configuration in `next.config.ts` to streamline the setup by removing redundant conditional checks. Additionally, improve error handling in `instrumentation.ts` by ensuring Sentry initialization is only enabled when the `SENTRY` environment variable is set. This enhances maintainability and ensures consistent behavior across environments.
> refactor: simplify Sentry configuration and improve error handling

- app/[locale]/(main)/admin/setting/image/page.tsx
Ensure consistent indentation and proper nesting of elements in the image card component to improve code readability and maintainability.
> refactor(admin): fix indentation and structure of image card buttons

- components/common/color-text.tsx
- components/common/message-list.tsx
Introduce a timeout to delay the scroll position adjustment after fetching new messages. This prevents janky scrolling behavior and improves the user experience. The timeout is cleared and reset on subsequent fetches to ensure smooth scrolling.
> refactor(message-list): add timeout for scroll position preservation

- components/common/message-list.tsx
- i18n/server.ts
Remove redundant backends array and directly configure HttpBackendOptions for improved readability and maintainability
> refactor(i18n): simplify backend options configuration

- app/[locale]/logic/add-file.dialog.tsx
- app/[locale]/logic/file.panel.tsx
- app/[locale]/logic/instruction.node.tsx
- app/[locale]/logic/logic-editor.context.tsx
- app/[locale]/logic/navbar.tsx
- app/[locale]/logic/no-file-open-screen.tsx
- app/[locale]/logic/search.panel.tsx
- app/[locale]/logic/sidebar.tsx
- app/[locale]/logic/style.css
- app/[locale]/logic/toolbar.tsx
- app/globals.css
- components/ui/sonner.tsx
Update color variables in globals.css for better consistency and add foreground colors for success and warning states. Refactor toast component in sonner.tsx to use updated color variables and improve readability by removing redundant text color classes.
> style(ui): adjust color variables and toast component styling

- app/[locale]/(main)/servers/[id]/(dashboard)/player-list.tsx
The empty line was added to separate the type definition and the function declaration, improving code readability and maintainability.
> style: add empty line for better readability in PlayerListSkeleton

- constant/constant.ts
- constant/env.ts
This change extends the list of accepted and supported image formats to include .gif, ensuring compatibility with GIF images in the application.
> feat(constant): add .gif to accepted and supported image formats

- app/[locale]/(main)/admin/setting/image/page.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/player-list.tsx
The grid gap in the player list component was increased from 1 to 4 to improve visual spacing between elements, enhancing readability and user experience.
> style(player-list): increase grid gap for better spacing

- app/[locale]/(main)/upload/admin/page.tsx
- Replace raw input with Input component for better consistency
- Update file handling to explicitly check for null or undefined
- Enhance list styling for better readability and UI consistency
> refactor(upload): improve file input handling and list styling

- app/[locale]/(main)/upload/admin/page.tsx
Introduce a progress bar to display the upload progress percentage. This enhances user experience by providing real-time feedback during file uploads. The `uploadFile` function now accepts an optional `onProgress` callback to update the progress state, which is reset upon success or error.
> feat(upload): add progress bar for file upload

- app/[locale]/(main)/translation/page.client.tsx
- components/plugin/plugin-card.tsx
- constant/constant.ts
Ensure the DeleteButton is properly wrapped in a ContextMenuItem to maintain consistent UI structure and behavior
> fix(plugin-card): add missing ContextMenuItem for DeleteButton

- app/[locale]/(main)/servers/[id]/logs/page.client.tsx
- app/[locale]/(main)/servers/[id]/logs/server-login-log-card.tsx
- components/common/nav-link.tsx
- components/ui/server-tabs.tsx
- Reduce opacity of unselected ServerTabsTrigger from 70 to 50
- Decrease border thickness of nav-link indicator from 3px to 2px
- Remove redundant animate prop and className from ServerTabsTrigger
- Refactor ServerLoginLogCard layout for improved readability and spacing
> style: adjust UI components for better visual consistency

- app/[locale]/(main)/servers/page.tsx
- app/[locale]/(main)/servers/server-list.tsx
- components/search/search-input.tsx
The change modifies the layout of the server list component to use `flex-col` instead of the default flex direction. This ensures better alignment and readability of the elements within the container.
> style(server-list): adjust layout to use flex-col for better alignment

- query/config/config.tsx
The error handling logic in the axios interceptor was refactored to better handle error responses. Specifically, the error message extraction was updated to use `error.response.data.message` instead of `error.response.message` for more accurate error reporting. Additionally, a `console.log` statement was added for debugging purposes.
> refactor(config): improve error handling in axios interceptor

- components/common/scroll-container.tsx
- components/search/mod-filter.tsx
- components/search/name-tag-search.tsx
- hooks/use-tags.ts
- In scroll-container.tsx, removed unnecessary state and refactored scroll handling into a function for better readability.
- In mod-filter.tsx, streamlined the selection logic to handle both multiple and single selections more efficiently, ensuring proper deselection when the same item is clicked.
> refactor: simplify scroll container logic and mod filter selection

- app/[locale]/(main)/users/[id]/user-detail.tsx
- app/globals.css
- components/button/verify.button.tsx
- components/like/like-button.tsx
- components/plugin/upload-plugin-preview-card.tsx
- components/ui/badge.tsx
- components/ui/switch.tsx
The success color variables were updated to improve readability and contrast. The new values ensure that the success text is more visible against its background.
> style(globals.css): update success color variables for better contrast

- app/[locale]/(main)/maps/[id]/page.tsx
- app/[locale]/(main)/schematics/[id]/page.tsx
- app/globals.css
- components/server/server-status.tsx
- components/ui/badge.tsx
- tailwind.config.ts
The tag names in the metadata descriptions were previously passed directly to the translation function, which could lead to issues with underscores and empty values. This change splits the tag names by underscores, filters out empty values, and maps each part to the translation function, ensuring cleaner and more accurate tag display.
> refactor: improve tag name formatting in metadata descriptions

- components/like/dislike-button.tsx
- components/ui/badge.tsx
Adjust the hover and active state colors of the dislike button to use `destructive-foreground` instead of `destructive` for improved visual alignment with the design system.
> style(like): update button styling for better visual consistency

- app/[locale]/(home)/page.tsx
- app/[locale]/(main)/image-generator/map/page.tsx
- app/[locale]/(main)/image-generator/router/page.tsx
- app/[locale]/(main)/maps/[id]/page.tsx
- app/[locale]/(main)/schematics/[id]/page.tsx
- components/ui/sonner.tsx
Removed the redundant border class in the toast component to simplify the styling. Updated the button variants to 'secondary' in the image-generator download buttons for consistency. Also improved alignment and spacing in the home page links by adding 'items-center' to the class names.Removed the redundant border class in the toast component to simplify the styling. Updated the button variants to 'secondary' in the image-generator download buttons for consistency. Also improved alignment and spacing in the home page links by adding 'items-center' to the class names.
> style(ui): remove redundant border class and adjust button variants

- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
- components/messages/member-pannel.tsx
The max-width class for the image in the dashboard was modified to apply only on medium screens and above (`md:max-w-[50dvw]`). This change ensures better responsiveness and alignment with the design requirements across different screen sizes.
> style: adjust image width for responsive design in dashboard

- app/[locale]/(main)/(shar)/files/page.tsx
- app/[locale]/(main)/nested-path-element-container.tsx
- app/[locale]/(main)/routes.tsx
- app/[locale]/(main)/translation/translation-status.tsx
- app/[locale]/auth/verify-player/success/page.tsx
- components/metric/login-history.tsx
- components/tag/multiple-filter-tags.tsx
- components/tag/single-filter-tags.tsx
- components/tag/tag-badge.tsx
- components/tag/tag-card.tsx
- types/response/UserLoginHistory.ts
This commit introduces the AddFolderDialog component to the file management interface, allowing users to create new folders within the specified path. This enhancement improves the user experience by providing a more comprehensive file management solution.
> feat(files): add AddFolderDialog component to file management interface

- next.config.ts
This change enables source maps in production builds to improve debugging capabilities by providing more detailed error information in the browser.
> build: enable production browser source maps

- app/[locale]/(main)/servers/[id]/(dashboard)/map-name-card.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/player-list.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/usage-card.tsx
- hooks/useServerStats.ts
- query/server.ts
- types/response/Server.ts
- types/response/ServerStats.ts
The comment for expirationTime was incorrectly stating "7 days" instead of "1 day". This commit fixes the comment to accurately reflect the value of 24 hours.
> fix(i18n): correct expirationTime comment in client.ts

- app/[locale]/(main)/servers/[id]/(dashboard)/usage-card.tsx
The changes ensure the usage card component takes up the full available space and uses a flex column layout for better alignment and responsiveness.
> style(usage-card): add full height and width with flex layout

- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
The PlayerList component's layout was adjusted to enhance its appearance and responsiveness. The changes include wrapping the grid in a flex container and ensuring consistent spacing and dimensions.
> style: improve layout and styling of PlayerList component

- app/[locale]/(main)/servers/[id]/maps/download-map-list.tsx
- app/[locale]/(main)/servers/[id]/plugins/download-plugin-list.tsx
- app/[locale]/(main)/servers/[id]/plugins/page.client.tsx
- app/[locale]/(main)/servers/[id]/plugins/plugin-list.tsx
- components/server/server-plugin-card.tsx
- components/tag/tag-container.tsx
- hooks/use-client.tsx
- lib/error.ts
- query/config/config.tsx
- types/response/Tag.ts
Removed development-specific logging in `use-client.tsx` to clean up production code. Simplified error handling in `query/config/config.tsx` by removing redundant try-catch blocks and consolidating error logging logic. These changes improve code maintainability and reduce unnecessary complexity.
> refactor: remove development logs and simplify error handling

- app/[locale]/(main)/servers/[id]/maps/download-map-list.tsx
- app/[locale]/(main)/servers/[id]/plugins/download-plugin-list.tsx
- components/metric/pie-chart.tsx
- components/plugin/plugin-card.tsx
- components/server/server-plugin-card.tsx
- constant/constant.ts
- lib/batcher.ts
- types/response/Plugin.ts
Enhance the plugin card UI by adding a GitHub icon fetched from the repository and displaying the last release date. The GitHub pattern is now centralized in the constants file for reuse across components. This improves user experience by providing more context about the plugin at a glance.
> feat(plugin-card): add GitHub icon and last release date to plugin card

- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/player-list.tsx
- components/metric/ram-usage-chart.tsx
- types/response/Player.ts
refactor(components): remove max-height constraint from ram-usage-chart
> feat(types): add isAdmin field to Player type

- app/[locale]/(main)/servers/[id]/players/page.client.tsx
- components/common/visibility.tsx
Refactor the visibility toggle components to simplify the conditional rendering logic. Additionally, update the IP masking regex to replace all digits with asterisks for enhanced privacy.
> refactor(visibility): simplify visibility toggle logic and IP masking

- app/[locale]/(main)/servers/[id]/layout.tsx
Add ErrorMessage and Skeleton components to handle error and loading states in the server layout. This improves user experience by providing feedback during data fetching and error scenarios.
> feat(servers): add error handling and loading state to server layout

- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
- components/common/catch-error.tsx
The `CatchError` component was moved to wrap only the relevant sections, improving error handling granularity. Additionally, the `KickList` import was reordered for better code organization.
> refactor(dashboard): reorganize component structure and error handling

- app/[locale]/(main)/servers/[id]/(dashboard)/kick-list.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
- app/[locale]/(main)/servers/server-list.tsx
The condition for displaying the ShutdownServerButton was updated to only show when the server status is 'HOST' or 'UP'. This ensures the button is not displayed unnecessarily when the server is in other states.
> fix: correct condition for displaying ShutdownServerButton

- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
The layout of the ScrollContainer was adjusted by replacing the grid with flex to improve the alignment and spacing of its children. This change ensures a more consistent and responsive design.
> style: replace grid with flex in ScrollContainer for better layout

- app/[locale]/(main)/users/[id]/user-detail.tsx
The changes include modifying the layout and overflow properties to ensure a more consistent and visually appealing user interface. Specifically, the overflow-hidden property was added to the main container to prevent content from spilling out, and the positioning of the inner div was adjusted to align elements correctly.
> style(user-detail): adjust layout and overflow for better UI consistency

- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
The Image component was replaced with a standard img tag to simplify the implementation and remove unnecessary width and height attributes, which were not required for the layout. This change improves maintainability without altering the visual behavior.
> refactor: replace Image component with img tag for server dashboard

- app/[locale]/(main)/servers/[id]/(dashboard)/player-list.tsx
This commit introduces a title and a divider to the player list component to improve the visual hierarchy and readability of the UI. The title is localized using the `Tran` component, ensuring it supports multiple languages.
> feat(player-list): add title and divider to player list component

- app/[locale]/(main)/servers/[id]/(dashboard)/kick-list.tsx
- components/server/ban.button.tsx
- components/server/kick.button.tsx
Refactored the import statements in `kick.button.tsx` to be more concise and consistent. Fixed the time display logic in `kick-list.tsx` to correctly show negative seconds instead of defaulting to '0s'.
> refactor: simplify import statements and fix time display logic

- app/[locale]/(main)/servers/[id]/(dashboard)/kick-list.tsx
- app/[locale]/(main)/test/page.tsx
- components/common/json-display.tsx
- components/server/server-plugin-card.tsx
This change simplifies the `TimeFrom` component by removing its internal state and relying on the `currentTime` prop passed from the parent. This improves performance by reducing unnecessary state updates and ensures consistency across the component tree.
> refactor(kick-list): replace dynamic state with currentTime prop

- components/map/map-detail-card.tsx
- components/map/upload-map-detail-card.tsx
Encapsulate the JsonDisplay component within a Dialog to improve user experience by providing a more organized and accessible way to view map metadata. This change applies to both MapDetailCard and UploadMapDetailCard components.
> feat(map): wrap JsonDisplay in Dialog for better UX

- app/globals.css
- components/common/comment-section.tsx
- components/common/created-at.tsx
- components/common/detail-swipe-to-navigate.tsx
- components/common/detail.tsx
- components/common/json-display.tsx
- components/common/size-card.tsx
- components/common/swipe-to-navigate.tsx
- components/map/map-detail-card.tsx
- components/map/upload-map-detail-card.tsx
- components/post/post-detail-card.tsx
- components/post/upload-post-detail-card.tsx
- components/schematic/schematic-detail-card.tsx
- components/schematic/upload-schematic-detail-card.tsx
- components/skeleton/detail.skeleton.tsx
- components/skeleton/user-card.skeleton.tsx
- components/tag/tag-card.tsx
- components/ui/tabs.tsx
- components/user/id-user-card.tsx
- components/user/user-avatar.tsx
- components/user/user-card.tsx
Refactored the detail components to improve layout consistency and added tabs for better organization of content. This includes changes to the detail structure, image handling, and the introduction of tabs for info, stats, and comments. Also, adjusted the styling and positioning of elements for a more cohesive user experience.
> refactor(detail): improve layout and add tabs for better organization

- components/skeleton/user-card.skeleton.tsx
Update the height and spacing in the user-card skeleton component to improve visual consistency and alignment with the design system.
> style(skeleton): adjust height and spacing in user-card skeleton

- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
- app/[locale]/(main)/servers/[id]/has-server-map.tsx
- app/[locale]/(main)/servers/[id]/host-server-button.tsx
- app/[locale]/(main)/servers/[id]/init-server-button.tsx
… handling
The ScrollContainer in the VerifyPluginDialog component is now wrapped in a Suspense component to improve loading behavior and ensure a smoother user experience during asynchronous operations.Reordered Tailwind CSS class names in the server dashboard page to improve consistency and maintainability. The changes do not affect the functionality but enhance the code's readability and alignment with Tailwind's recommended class ordering.
> style: reorder class names for consistency and readability

- components/common/detail.tsx
- components/skeleton/detail.skeleton.tsx
Reordered class names in multiple components to maintain a consistent and readable structure. This change does not affect the functionality but improves the code maintainability and aligns with the project's styling conventions.
> style(components): reorder class names for consistency and readability

- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
- components/server/server-plugin-card.tsx
This change adds a bounce animation to the button in the server plugin card to enhance user interaction and visual feedback when the button is clicked.
> style(server-plugin-card): add bounce animation to button

- components/common/relative-time.tsx
Introduce `useState` and `useInterval` to dynamically update the relative time display. This ensures the time is refreshed periodically, improving the user experience by keeping the displayed time accurate without requiring a page reload.
> feat(relative-time): add dynamic time updates using useInterval

- app/[locale]/(main)/chat/page.client.tsx
- components/common/infinite-page.tsx
- components/messages/member-pannel.tsx
Clean up MemberPanel component by removing unused noResult and end props
Remove unnecessary dynamic import of EmojiPicker component that wasn't being used
> refactor(components): remove unused props and dynamic import

- app/[locale]/(main)/servers/[id]/(dashboard)/chat-list.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/chat-panel.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/has-server-map.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
- app/[locale]/(main)/servers/[id]/console/page.client.tsx
- app/[locale]/(main)/servers/[id]/console/page.tsx
- app/[locale]/(main)/servers/[id]/players/page.client.tsx
- components/server/ban.button.tsx
- components/server/kick.button.tsx
Check server status using useServerStatus hook and display offline message if server is unavailable. This prevents unnecessary API calls and improves user experience when server is offline.
> feat(players): add server status check before rendering players page

- app/[locale]/(main)/servers/[id]/(dashboard)/chat-panel.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/init-server-button.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
- app/[locale]/(main)/servers/[id]/setting/server-update-form.tsx
- app/[locale]/(main)/servers/not-found.tsx
- components/metric/pie-chart.tsx
- components/ui/ellipsis-button.tsx
- i18n/server.ts
- next.config.ts
- package.json
The DotsHorizontalIcon was missing a size class, causing inconsistent sizing. Added 'size-4' class to maintain visual consistency with other icons in the UI.
> style(ui): add size class to ellipsis button icon

- app/[locale]/(main)/servers/[id]/(dashboard)/chat-list.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/chat-panel.tsx
Remove max-h-screen from MessageList to prevent double scrollbars Add max-h-screen to ChatPanel container for consistent height control
> style(chat): adjust height and layout classes in chat components

- app/[locale]/(main)/servers/[id]/(dashboard)/pause-server-button.tsx
- app/[locale]/(main)/users/[id]/me.tsx
- app/[locale]/(main)/users/[id]/other.tsx
- components/button/delete.button.tsx
- components/button/download.button.tsx
- components/button/verify.button.tsx
- components/common/infinite-page.tsx
- components/map/delete-map.button.tsx
- components/map/take-down-map.button.tsx
- components/map/verify-map.button.tsx
- components/post/post-detail-card.tsx
- components/post/upload-post-detail-card.tsx
- components/schematic/take-down-schematic.button.tsx
- components/schematic/verify-schematic.button.tsx
- constant/constant.ts
The PauseIcon was rendered but never used in the component's logic since the button shows PlayIcon when the server is paused. Removing it simplifies the component and avoids confusion.
> refactor(pause-server-button): remove unused PauseIcon component

- app/[locale]/(main)/server-managers/[id]/layout.tsx
- app/[locale]/(main)/server-managers/[id]/maps/page.tsx
- app/[locale]/(main)/server-managers/[id]/page.tsx
- app/[locale]/(main)/server-managers/[id]/plugins/page.tsx
- app/[locale]/(main)/server-managers/page.tsx
- app/[locale]/(main)/servers/create-server-manager.dialog.tsx
- app/[locale]/(main)/servers/create-server.dialog.tsx
- constant/constant.ts
- hooks/use-server-manager.ts
- query/server-manager.ts
- query/server.ts
- types/response/ServerManagerMap.ts
- types/response/ServerManagerPlugin.ts
- Create new types for server manager maps and plugins
- Add new hook for server manager data fetching
- Move server manager related queries to separate file
- Implement UI for managing server manager maps and plugins
- Improve server manager detail page layout and functionality
- Add navigation layout for server manager subpages
- Add new color constant 'sky'
> feat(server-manager): add server manager management features

- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
- app/[locale]/(main)/servers/[id]/plugins/page.client.tsx
The DownloadPluginList component is now wrapped in Suspense to enable lazy loading, improving the initial page load performance by deferring the loading of this component until it's needed.
> refactor(plugins): wrap DownloadPluginList in Suspense for lazy loading

- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
- app/[locale]/(main)/servers/[id]/layout.tsx
- app/[locale]/(main)/servers/[id]/setting/page.tsx
- app/[locale]/layout.tsx
The PauseServerButton was moved after the status-dependent action buttons to create a more logical visual hierarchy and improve user experience when interacting with server controls.
> refactor(servers): reorder server action buttons for better UI flow

- app/[locale]/(main)/schematics/page.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/mismatch-panel.tsx
- Implement unstable_cache for schematics data to improve performance with 1-hour revalidation
- Add schematic images to openGraph metadata in generateMetadata
> feat(schematics): add caching and images to metadata generation

- app/[locale]/(main)/maps/page.tsx
- Implement unstable_cache for maps data with 1-hour revalidation
- Add openGraph metadata with map images and descriptions
- Include server-side data fetching for metadata generation
> feat(maps): add caching and metadata enhancements for maps page

- app/[locale]/(main)/servers/[id]/maps/download-map-list.tsx
- app/[locale]/(main)/servers/[id]/stats/page.tsx
Include minimum and maximum values in the chart label to provide more comprehensive statistics at a glance
> feat(stats): add min/max values to server stats chart label

- app/[locale]/(main)/admin/setting/roles/change-role-authority.dialog.tsx
- lib/utils.ts
Remove conditional filtering based on session roles to use direct data assignment
> refactor(admin): simplify authority filtering logic

- app/[locale]/(main)/servers/[id]/(dashboard)/mismatch-panel.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
- app/[locale]/(main)/servers/[id]/setting/server-plan-list.tsx
- app/[locale]/(main)/servers/[id]/setting/server-update-admin-form.tsx
- app/[locale]/(main)/servers/[id]/setting/server-update-form.tsx
- app/[locale]/(main)/servers/[id]/stats/page.tsx
- app/[locale]/logic/file.panel.tsx
- app/[locale]/logic/instruction.node.tsx
- app/[locale]/logic/live-code-panel.tsx
- app/[locale]/logic/logic-editor.context.tsx
- app/[locale]/logic/plus.panel.tsx
- app/[locale]/logic/sidebar.tsx
- app/[locale]/logic/toolbar.tsx
- components/common/input-with-autocomplete.tsx
- components/log/log-card.tsx
- components/server/server-plugin-card.tsx
- query/server.ts
- types/response/ServerDto.ts
- types/response/ServerSetting.ts
The maxTick prop was unnecessary as the chart can automatically adjust its scale based on the dataThe maxTick prop was unnecessary as the chart can automatically adjust its scale based on the data
> fix(stats): remove maxTick prop from LineChart component

- app/[locale]/layout.tsx
- context/session.context.tsx
- Replace dynamic import with direct import for ClientInit
- Simplify session fetching logic using fetch API and preloading
- Remove unnecessary axios dependency and useEffect
> refactor(session): optimize session fetching and client initialization

- app/[locale]/layout.tsx
- context/session.context.tsx
- hooks/use-config.ts
Add check for undefined window to prevent server-side execution of client-side code. Also fix optional chaining for session promise resolution.
> fix(session): handle undefined window in preloadSession

- components/common/json-display.tsx
Add null check for object type to prevent rendering issues and correct length comparison for object entries
> fix(json-display): handle null values and fix object length check

- components/ui/ellipsis-button.tsx
- Change single quotes to double quotes for consistency
- Update popover content styling with secondary background and margin
> style(ui): update ellipsis button styling and spacing

- app/[locale]/(main)/servers/[id]/(dashboard)/host-server-button.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/init-server-button.tsx
- hooks/use-http-stream.ts
- hooks/use-sse.ts
- Add timestamp calculation and display for log entries
- Include index numbering for better log traceability
- Update data structure to store creation timestamps
> feat(server-dashboard): enhance log display with timestamps and indexes

- app/[locale]/(main)/servers/[id]/(dashboard)/host-server-button.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/init-server-button.tsx
- hooks/use-sse.ts
Avoid creating multiple EventSource instances by checking if one already exists before creating a new one
> fix(use-sse): prevent duplicate EventSource creation

- context/socket.context.tsx
Remove dependency on session context for socket connection and streamline connection state handling. Add explicit connected state check and cleanup effect dependencies.
> refactor(socket): remove auth dependency and simplify connection logic

- app/[locale]/(main)/servers/[id]/(dashboard)/host-server-button.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/init-server-button.tsx
- context/socket.context.tsx
- Replace space-x-2 with gap-2 for consistent spacing
- Format index with leading zeros for alignment
- Move timestamp outside of bold span for better readability
> refactor(server-dashboard): improve log entry formatting consistency

- app/[locale]/(main)/servers/[id]/(dashboard)/host-server-button.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/init-server-button.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/stream-text-card.tsx
- hooks/use-http-stream.ts
Create reusable StreamTextCard component to display stream data consistently across host-server-button and init-server-button. Also export StreamData type from use-http-stream hook for better type sharing.
> feat(dashboard): extract stream text card component for reuse

- action/common.ts
- hooks/use-http-stream.ts
- hooks/use-mindustry-gpt.tsx
- i18n/client.ts
- i18n/server.ts
- lib/error.ts
Wrap fetch operations in try-catch blocks to properly handle errors and provide more descriptive error messages. This improves error tracking and user feedback when network requests fail.
Also clean up redundant whitespace and improve code organization in modified files.
> refactor(http): add error handling for fetch operations

- i18n/client.ts
- i18n/server.ts
The error logging in both client and server translation fetching was enhanced to properly stringify error objects, providing more detailed error information for debugging purposes.
> fix(i18n): improve error logging by stringifying error objects

- i18n/client.ts
- i18n/server.ts
Include response body in error message to help debug translation fetch failures
> fix(i18n): improve error message for failed translations fetch

- hooks/use-user.ts
- i18n/client.ts
- i18n/server.ts
- lib/utils.ts
Implement withRetry utility function and apply it to both client and server translation fetching. This improves reliability by automatically retrying failed requests up to 3 times before giving up. Also remove retry: false from useUser hook as it's no longer needed with the new retry mechanism.
> feat(i18n): add retry mechanism for translation fetching

- context/session.context.tsx
- types/response/Role.ts
- types/response/Session.ts
- Replace manual type definitions with zod schemas for better validation
- Add schema parsing in session context for type safety
- Persist session state in local storage with schema validation
> refactor(auth): migrate session and role types to zod schemas

- components/common/report-error.form.tsx
- context/session.context.tsx
- query/comment.ts
- query/tag.ts
- query/user.ts
- types/request/CreateServerRequest.ts
- types/response/Session.ts
- types/response/WorkflowContext.ts
- types/schema/search-query.ts
Add error to errors array when authentication fails to maintain error history and improve debugging
> fix(session): handle and store authentication errors

- app/[locale]/(main)/maps/[id]/page.tsx
- app/[locale]/(main)/schematics/[id]/page.tsx
- components/common/scroll-container.tsx
- context/session.context.tsx
- lib/error.ts
- Enhance error messages with descriptive context in console logs
- Reorganize metadata imports in page components
- Add revalidation time to dynamic pages
> refactor: improve error logging and metadata organization

- app/[locale]/(main)/servers/[id]/(dashboard)/usage-panel.tsx
- components/common/grid-pagination-list.tsx
- components/common/no-result.tsx
- components/search/name-tag-search.tsx
- components/server/kick.button.tsx
- hooks/use-sse.ts
Add useEffect to automatically reconnect when the SSE connection state changes to disconnected
> fix(use-sse): reconnect when state is disconnected

- app/[locale]/(main)/servers/[id]/(dashboard)/usage-panel.tsx
- constant/constant.ts
- lib/error.ts
Add stack trace to error logging to help with debugging by providing more context about where errors occur
> fix(error): include stack trace in request error logging
