sharrlotte/MindustryToolNext

- app/[locale]/(main)/image-generator/router/page.tsx
This commit introduces a `Button` component to manually trigger the image processing mutation. Previously, the mutation was automatically triggered when an image was selected. This change provides users with more control over when the image processing starts.
> feat(image-generator): add process button to trigger image mutation

- app/[locale]/(main)/image-generator/router/page.tsx
Move the preview generation logic from the main page component to a dedicated `Preview` component to improve code maintainability and separation of concerns.
> refactor(image-generator): extract preview logic into separate component

- components/common/message-list.tsx
- hooks/use-message-query.ts
The socket state check was redundant as it did not affect the rendering logic. Simplifying the condition improves code clarity and maintainability.
> refactor(message-list): remove unused socket state check

- app/[locale]/(main)/admin/setting/layout.tsx
The gap between grid rows was redundant and caused layout inconsistencies. Removing it ensures a cleaner and more consistent UI.
> style(layout): remove unnecessary gap in admin setting layout

- hooks/use-client.tsx
The axios interceptor was not returning a rejected promise, which could lead to unhandled errors in the application. This commit ensures that errors are properly rejected by returning `Promise.reject(error)` in the interceptor.
> fix(use-client): ensure error rejection in axios interceptor

- components/ui/sonner.tsx
The border-transparent class was redundant and unnecessary in the toast component styling. This change simplifies the CSS by removing it, improving code readability and maintainability.
> style(sonner): remove redundant border-transparent class

- app/[locale]/(main)/admin/maps/page.client.tsx
- app/[locale]/(main)/admin/schematics/page.client.tsx
- app/[locale]/(main)/maps/page.tsx
- app/[locale]/(main)/schematics/page.tsx
- components/common/pagination-layout.tsx
The flex-wrap property was removed from multiple pagination layout components to ensure consistent styling across the application. This change aligns the layout behavior and improves visual consistency.
> style: remove flex-wrap from pagination layout for consistency

- app/[locale]/(main)/servers/community-server.tsx
- app/[locale]/(main)/servers/my-server.tsx
- app/[locale]/(main)/servers/official-server.tsx
- app/[locale]/(main)/servers/page.footer.tsx
- app/[locale]/(main)/servers/page.tsx
- app/[locale]/(main)/servers/servers-skeleton.tsx
- components/server/server-card.tsx
- layout/client-protected-element.tsx
- query/server.ts
Refactor server-related components to use client-side rendering for better performance and user experience. This includes moving `ServerCard`, `OfficialServer`, `CommunityServer`, and `MeServer` to client components, introducing `ClientProtectedElement`, and adding skeleton loading states. The changes also simplify the server page structure and improve code maintainability.
> refactor(servers): migrate server components to client-side rendering

- app/[locale]/(main)/servers/community-server.tsx
The official parameter in the queryFn was incorrectly set to true, causing the community server to only display official servers. This change ensures that all community servers are displayed as intended.
> fix(community-server): set official parameter to false in queryFn

- .eslintrc.json
- .prettierrc
- app/[locale]/logic/instruction.node.tsx
- app/[locale]/logic/logic-editor-context.tsx
- app/[locale]/logic/node.tsx
- app/[locale]/logic/page.tsx
- app/[locale]/logic/toolbar.tsx
- components/common/catch-error.tsx
Introduce toggleable minimap and live code panel features in the logic editor. These features can be enabled/disabled via toolbar buttons or shortcuts (Ctrl+M for minimap, Ctrl+L for live code panel). The visibility state is persisted in local storage. Additionally, refactor the instruction node component to improve maintainability and fix minor styling issues.
> feat(logic-editor): add toggleable minimap and live code panel

- app/[locale]/logic/instruction.node.tsx
- app/[locale]/logic/logic-editor-context.tsx
- app/[locale]/logic/page.tsx
- app/[locale]/logic/sidebar.tsx
- app/[locale]/logic/toolbar.tsx
Ensure that the `filterdItems` logic correctly handles cases where `condition` is undefined, preventing potential runtime errors. Additionally, adjust the import order and formatting in the logic editor context for better readability.
> fix(logic): handle undefined condition in instruction node filtering

- components/button/copy-button.tsx
- components/ui/button.tsx
The hover background color for command buttons was updated to use a more consistent and visually appealing `destructive/80` shade. This change ensures better alignment with the design system and improves the user experience.
> style(button): update command button hover background color

- app/[locale]/logic/node.tsx
Restructured the instructionNodesGraph by moving the 'if' node and adding new nodes ('wait', 'stop', 'drawFlush'). Introduced a type `InstructionCategory` to improve type safety and readability. These changes enhance maintainability and clarity of the codebase.
> refactor(logic/node): reorganize instructionNodesGraph and add new nodes

- app/[locale]/(main)/admin/setting/image/page.tsx
- query/image.ts
Introduce `onUploadProgress` callback to the `uploadImage` function to track upload progress. Display progress bars for each file being uploaded in the UI. This improves user experience by providing real-time feedback on the upload status.
> feat(upload): add upload progress tracking for image uploads

- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
- types/response/ServerDto.ts
The condition for displaying the RemoveServerButton was updated from checking if the status is not 'HOST' to checking if the status is not 'DELETED'. This ensures the button is displayed correctly based on the server's lifecycle state. Additionally, the ServerStatus type was updated to include 'DELETED' as a valid status.
> fix(servers): correct server status check for RemoveServerButton

- app/[locale]/(main)/servers/[id]/setting/server-update-form.tsx
- types/request/UpdateServerRequest.ts
- types/response/Server.ts
Add an `image` field to the `Server` interface and `PutServerSchema` to support server image selection. Update the server update form to include a combo box for selecting an image from a list of available server images.
> feat(server): add image field to server update form and types

- app/[locale]/(main)/admin/setting/image/page.tsx
- hooks/use-query-state.ts
- query/config/config.ts
Ensure that the error is logged before rejecting the promise in the axios response interceptor. This prevents the error from being lost if the promise is rejected prematurely.
> fix: log error before rejecting promise in axios interceptor

- app/[locale]/logic/node.tsx
- app/[locale]/logic/plus.panel.tsx
- components/server/server-card.tsx
The CopyButton component and the address prop were removed as they were no longer used in the ServerCard component. This simplifies the component and reduces unnecessary code.
> refactor(server-card): remove unused CopyButton and address prop

- components/server/server-card.tsx
This change ensures that the map name text does not wrap, improving readability and layout consistency in the server card component.
> style(server-card): add text-nowrap to map name container

- components/server/server-status.tsx
The previous implementation displayed "Unknown" for unrecognized server statuses, which was not user-friendly. This change replaces it with a `Badge` component that visually indicates the status, improving the user experience by making it clear when the server status is unexpected.
> fix(server-status): replace unknown status with Badge component

- app/[locale]/(main)/upload/admin/layout.tsx
- app/[locale]/(main)/upload/admin/page.tsx
- constant/constant.ts
Introduce a new admin upload panel for managing file uploads, including a form for file submission and a list to display uploads in different states (QUEUING, PROCESSING, ERROR). Add `uploadStates` constant to define these states.
> feat(upload): add admin upload panel and upload states constants

- app/[locale]/(main)/upload/admin/page.tsx
Simplify API endpoint paths by removing unnecessary prefixes. This change improves consistency and reduces redundancy in the API calls.
> refactor(api): update API endpoint paths in upload admin page

- app/[locale]/(main)/upload/admin/page.tsx
This change improves the visual spacing of file list items by increasing the padding from `p-1` to `p-2`, enhancing readability and user experience.
> style: increase padding for file list items in upload admin page

- app/[locale]/(main)/admin/documents/create-document-tree.dialog.tsx
- app/[locale]/(main)/admin/documents/page.tsx
- app/[locale]/(main)/routes.tsx
- app/[locale]/(main)/upload/admin/page.tsx
- app/[locale]/documents/page.tsx
- app/[locale]/logic/search.panel.tsx
- query/document.ts
- types/response/DocumentDto.ts
This commit introduces a new documents page and its related components, including the `DocumentDto` type, `CreateDocumentTreeDialog`, and the main documents page under the admin section. Additionally, it adds a new route for documents in the main routes configuration and enhances the search panel with a background highlight for the filter term.
> feat(documents): add documents page and related components

- app/[locale]/(main)/admin/setting/image/page.tsx
This commit updates the upload functionality to sanitize filenames, ensuring they conform to valid Ubuntu filename standards. The filename is now processed to replace invalid characters and remove leading/trailing special characters, enhancing the reliability of file uploads.
> fix(upload): sanitize filenames for valid uploads

- app/[locale]/(main)/users/[id]/page.tsx
- components/user/user-avatar.tsx
Enhance the user metadata generation to support multiple images by including both `thumbnail` and `imageUrl` in the `openGraph` images array. This improves the display of user profiles by providing more visual context.
> feat(users): add support for multiple images in user metadata

- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
- constant/constant.ts
The flag for the VI locale was incorrectly set to '🇻🇮' instead of '🇻🇳'. This commit fixes the flag to ensure it matches the correct country code.
> fix(constant): correct flag for VI locale

- app/[locale]/(main)/admin/setting/image/page.tsx
The padding in card components (`DirCard`, `FileCard`, and `ImageCard`) was reduced from `p-2` to `p-1` to maintain visual consistency across the application and improve alignment with the design system.
> style: reduce padding in card components for consistency

- components/server/ban.button.tsx
The ban command syntax was updated to include the 'add' keyword to align with the server's expected command for
> fix(server): update ban command syntax to include 'add' keyword

- app/[locale]/(main)/translation/compare.table.tsx
- app/[locale]/(main)/translation/diff-table.tsx
- app/[locale]/(main)/translation/page.client.tsx
- app/[locale]/(main)/translation/search.table.tsx
- hooks/use-search-query.ts
Include the paginationSize from the session context in the search query result to ensure consistent pagination behavior across the application. This change modifies the useSearchQuery hook to dynamically adjust the query size based on the user's session configuration.
> feat(hooks): add paginationSize from session to search query

- app/[locale]/(main)/servers/[id]/(dashboard)/player-list.tsx
The padding was changed from `px-4` to `p-4` to ensure consistent padding on all sides of the container. This improves visual alignment and follows design system guidelines.
> style: update padding in player-list component for consistency

- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/player-list.tsx
The `h-full` class was redundant in the server dashboard layout as it did not affect the layout behavior. Removing it improves code readability and maintains consistency in the styling.
> style: remove redundant `h-full` class from server dashboard layout

- app/[locale]/(main)/servers/page.tsx
- app/[locale]/(main)/servers/server-list.tsx
The height property was unnecessarily set to "h-full" in grid containers, which was redundant since the grid layout already handles the height appropriately. This change improves code readability and maintains consistent styling.
> style: remove redundant height property from grid containers

- components/search/name-tag-search.tsx
The `max-h-[50dvh]` class was added to the `ScrollContainer` to limit its height, improving the user experience by preventing the container from becoming too large and overwhelming the interface.
> style(search): add max height to scroll container for better UX

- components/common/bulk-action.tsx
The size of SquareIcon was incorrectly set to 'size-10', which caused inconsistency with SquareCheckedIcon. This fix ensures both icons have the same size ('size-6') for a uniform appearance.
> fix(bulk-action): correct size of SquareIcon to match SquareCheckedIcon

- app/[locale]/(main)/translation/all.table.tsx
- app/[locale]/(main)/translation/page.client.tsx
- query/translation.ts
- types/response/Translation.ts
- types/schema/search-query.ts
This commit introduces a new feature that allows users to view all translations in a table format. The changes include:
- Adding a new `AllTable` component to display translations
- Extending the schema and response types to support the new feature
- Updating the translation page to include the new table mode
> feat(translation): add support for viewing all translations in a table

- query/config/config.tsx
Remove redundant try-catch block and directly handle error response message. This improves code readability and reduces unnecessary nesting.
> refactor: simplify error handling in axios interceptor

- app/[locale]/(main)/maps/[id]/page.tsx
- app/[locale]/(main)/schematics/[id]/page.tsx
- app/[locale]/layout.tsx
Add siteName to metadata in layout and include downloadCount, likes, and dislikes in openGraph descriptions for maps and schematics pages to provide more detailed information
> feat(metadata): enhance openGraph descriptions with stats

- app/[locale]/(main)/maps/[id]/page.tsx
- app/[locale]/(main)/schematics/[id]/page.tsx
Enhance the openGraph metadata for maps and schematics by including authors and tags. This improves the richness of the metadata, providing more context and discoverability for shared links.
> feat(metadata): add authors and tags to openGraph metadata

- app/[locale]/(main)/maps/[id]/page.tsx
- app/[locale]/(main)/schematics/[id]/page.tsx
Enhance metadata generation for maps and schematics by including the author's name and tags in the openGraph description. This improves the richness of the metadata displayed when sharing links to these pages.
> feat(metadata): add author name and tags to openGraph description

- app/[locale]/(main)/maps/[id]/page.tsx
- app/[locale]/(main)/schematics/[id]/page.tsx
- i18n/client.ts
- i18n/server.ts
This commit introduces translation support for tags in the metadata generation of maps and schematics pages. The `getTranslation` function is now used to translate tag names, improving localization for international users.
> feat(i18n): add translation support for tags in metadata

- app/[locale]/(main)/admin/setting/mods/update-mod.dialog.tsx
- components/search/mod-filter.tsx
- components/search/name-tag-search.tsx
- components/search/tag-selector.tsx
- hooks/use-tags.ts
- query/mod.ts
- types/response/Mod.ts
This commit introduces the ability to select multiple mods in the mod filter component. The changes include updating the state to handle an array of mods, modifying the `ModFilter` component to support multiple selections, and adjusting related components and hooks to accommodate this new functionality. This enhancement improves the user experience by allowing more flexible filtering options.
> feat(mod-filter): support multiple mod selection in filter component

- components/search/mod-filter.tsx
The previous implementation did not handle deselection correctly for multiple values. This fix ensures that when a mod is already selected in a multiple selection scenario, it is properly removed from the list instead of being added again.
> fix(search): correct mod filter selection logic for multiple values

- app/[locale]/(main)/medium-nav.footer.tsx
- app/[locale]/(main)/medium-navigation-items.tsx
- app/[locale]/(main)/navbar-link.tsx
- app/[locale]/(main)/nested-path-element-container.tsx
- app/[locale]/docs/doc-type.ts
- i18n/server.ts
The React cache was removed from the `readDocs` and `getTranslation` functions to simplify the code and avoid unnecessary caching. This change improves maintainability and reduces complexity without altering the core functionality.
> refactor: remove React cache from readDocs and getTranslation

- app/[locale]/(main)/medium-navigation-items.tsx
Remove redundant NavbarVisible and span elements to streamline the rendering logic for navigation items
> refactor(medium-navigation-items): simplify PathGroupElement rendering

- app/[locale]/layout.tsx
- components/file/file-card.tsx
The previous condition `if (!directory)` was incorrectly rendering the file data based on the directory flag. This change updates the condition to `if (data !== null)` to ensure the file data is rendered correctly when it exists, regardless of whether the file is a directory or not.
> fix(file-card): correct conditional rendering logic for file data

- app/[locale]/(main)/logs/page.client.tsx
- context/session.context.tsx
- Change default log collection from 'SERVER' to 'SYSTEM' to align with system logs
- Add null check for session data to prevent undefined state in session context
> fix: update default log collection and handle null session data

- components/tag/multiple-filter-tags.tsx
- components/tag/single-filter-tags.tsx
- components/tag/tag-badge.tsx
- components/tag/tag-card.tsx
The change replaces hyphens with underscores in tag names across multiple components to maintain consistency and improve readability. This modification affects TagCard, TagBadge, MultipleFilterTags, and SingleFilterTags components.
> refactor(tag): replace hyphen with underscore in tag names

- app/[locale]/(main)/admin/setting/tags/page.client.tsx
- app/[locale]/(main)/maps/[id]/page.tsx
- app/[locale]/(main)/schematics/[id]/page.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
- components/tag/filter-tags.tsx
- components/tag/tag-card.tsx
- components/tag/tag-tooltip.tsx
The RamUsageChart component expects values in bytes, but the data was being passed in megabytes. This commit multiplies the ramUsage and totalRam values by 1024 * 1024 to convert them from megabytes to bytes, ensuring the chart displays accurate information.
> fix: convert RAM usage values to bytes for accurate chart display

- .env.production
The request timeout was increased from 1000ms to 3000ms to accommodate slower network conditions and reduce the likelihood of timeout errors in production.
> chore: increase request timeout to 3000ms

- .env.production
The request timeout was increased to 15000 to accommodate slower network conditions and improve reliability in production environments.
> chore: increase request timeout to 15000 for production

- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
The comment for expirationTime was incorrectly stating "7 days" instead of "1 day". This commit fixes the comment to accurately reflect the value of 24 hours.
> fix(i18n): correct expirationTime comment in client.ts

- context/socket.context.tsx
Separate the socket cleanup logic into its own useEffect to improve code clarity and maintainability. This ensures the cleanup only depends on the socket and not on authState, reducing unnecessary re-renders.
> refactor(socket): separate cleanup effect in SocketProvider

- app/[locale]/(main)/servers/[id]/plugins/download-plugin-list.tsx
The console.log statement was removed to clean up the code and improve maintainability. This change does not affect the functionality of the component.
> refactor: remove console.log statement from AddServerPluginCard

- components/server/server-plugin-card.tsx
Add the filename to the server plugin card to provide more context about the plugin being displayed. This helps users quickly identify the specific plugin file associated with the card.
> feat(server-plugin-card): display filename in plugin card

- app/[locale]/(main)/posts/page.client.tsx
- app/[locale]/(main)/posts/page.tsx
- app/[locale]/(main)/upload/post/page.tsx
Refactor the posts page to remove the initial data props and simplify the logic by relying on the `InfinitePage` component to fetch data directly. This improves maintainability and reduces unnecessary data passing between components. Additionally, update the upload post page to improve UI consistency by adding headers and dividers.
> refactor(posts): remove initial data props and simplify page logic

- app/[locale]/(main)/servers/[id]/layout.tsx
The previous code incorrectly split plugin filenames using '_)' as the delimiter, which caused parsing issues. This commit fixes the delimiter to '_' to ensure proper parsing of plugin filenames.
> fix: correct plugin filename parsing by removing extra character

- app/[locale]/(main)/servers/[id]/layout.tsx
Refactor the plugin label data mapping to include both id and version as an object. This enhances readability and prepares for future extensions where both fields might be needed.
> refactor(servers): improve plugin label data structure

- app/[locale]/(main)/servers/[id]/layout.tsx
- app/[locale]/(main)/servers/[id]/players/page.client.tsx
- app/[locale]/(main)/servers/[id]/players/page.tsx
- types/schema/search-query.ts
Introduce a new page for managing players within a server, including a filter to view banned or non-banned players. The page displays player details such as last IP, known names, and admin status. This enhancement improves server administration capabilities by providing a centralized view of player information.
> feat(players): add player management page with ban status filter

- app/[locale]/(main)/servers/[id]/plugins/download-plugin-list.tsx
- components/server/server-plugin-card.tsx
Ensure the plugin-version cache is invalidated after plugin-related operations to maintain data consistency and avoid stale data.
> fix: invalidate plugin-version cache after plugin operations

- app/[locale]/(main)/servers/[id]/layout.tsx
- app/[locale]/(main)/servers/[id]/plugins/download-plugin-list.tsx
- components/server/server-plugin-card.tsx
The query key for the plugin version was missing the `data` dependency, which could lead to stale or incorrect cache results. Adding `data` ensures the query is correctly invalidated when the data changes.
> fix(servers): include data in plugin version query key

- app/[locale]/(main)/servers/[id]/logs/server-build-log-card.tsx
- app/[locale]/(main)/servers/[id]/logs/server-login-log-card.tsx
- app/[locale]/(main)/servers/[id]/players/page.client.tsx
Improve consistency and maintainability by wrapping all UUID and IP visibility text in span tags across multiple components. This ensures uniform styling and structure for visibility toggles.
> refactor: wrap UUID and IP visibility text in span tags

- app/[locale]/(main)/servers/[id]/(dashboard)/player-list.tsx
- components/common/catch-error.tsx
The previous implementation would set a relative time string even when the seconds value was zero, which is unnecessary and could lead to misleading display. This change ensures that the relative time is only set when there are positive seconds remaining.
> fix(player-list): prevent setting relative time for zero seconds

- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
The max-height of the ScrollContainer was changed from '50vh' to '500px' to ensure a more consistent and predictable layout across different screen sizes. This adjustment improves the user experience by preventing excessive scrolling on smaller screens.
> style: adjust max-height of ScrollContainer for better UI consistency

- app/[locale]/(main)/servers/[id]/plugins/download-plugin-list.tsx
- components/server/server-plugin-card.tsx
The height of plugin cards was increased from 40 to 48 units to improve visibility and readability of the content within the cards. This change was applied consistently across all related components to maintain a uniform UI experience.
> style(ui): increase height of plugin cards for better visibility

- components/common/json-display.tsx
The JSON.parse was redundant since the input `json` is already a parsed object. This change avoids unnecessary double parsing, which could lead to errors if the input is not a valid JSON string.
> fix(json-display): remove redundant JSON.parse to prevent double parsing

- components/common/json-display.tsx
Add `text-wrap` and `w-full` classes to ensure proper text wrapping and full width. Use tab character for indentation to enhance readability.
> style(json-display): improve readability and formatting of JSON display

- app/[locale]/(main)/servers/[id]/(dashboard)/kick-list.tsx
Added a filter to the kick list to ensure only active kicks (those with `untilTime` greater than the current time) are displayed. This prevents outdated or expired kicks from showing up in the UI.
> fix(kick-list): filter out expired kicks to prevent display

- app/[locale]/(main)/servers/[id]/setting/server-update-form.tsx
- i18n/client.ts
- i18n/server.ts
This change appends a version query parameter (`v=1`) to the translation load paths in both client and server configurations to ensure the latest translations are fetched and avoid caching issues. Additionally, a minor whitespace fix was applied in the server update form.
> fix(i18n): add version query param to translation load paths

- components/ui/sonner.tsx
The toast position was not explicitly set, causing it to default to a potentially undesired location. This change ensures the toast always appears in the top-right corner for better user experience.
> fix(sonner): set toast position to top-right

- app/[locale]/(main)/servers/server-list.tsx
Remove redundant padding from the grid container and add padding to the parent div to improve overall spacing and alignment in the server list component.
> style(server-list): adjust padding and grid layout for better spacing

- components/server/server-plugin-card.tsx
Avoid rendering the PluginVersion component when the version prop matches the fetched data version to prevent unnecessary UI updates.
> fix(server-plugin-card): skip rendering if version matches data

- components/button/delete.button.tsx
The `w-fit` class was added to the secondary button variant to ensure the width of the button fits its content, improving visual consistency and alignment with other button styles.
> style(button): adjust secondary button width to fit content

- components/user/user-avatar.tsx
The h-fit class was added to the InternalLink component within the UserAvatar to ensure consistent sizing and alignment of the avatar image. This change improves the visual consistency of the component without altering its functionality.
> style(user-avatar): add h-fit class to InternalLink for better sizing

- app/[locale]/(main)/servers/[id]/plugins/plugin-list.tsx
- types/response/Message.ts
The check for empty or newline message content was removed to simplify the grouping logic. This change ensures all messages are processed uniformly, improving code maintainability.
> refactor(types): remove empty message content check in groupMessage

- app/[locale]/(main)/servers/[id]/metrics/page.tsx
The default filter was incorrectly set to metricFilters[0], which caused the metrics page to display incorrect data initially. This change sets the default filter to metricFilters[4] to ensure the correct data is shown when the page loads.
> fix(metrics): set default filter to metricFilters[4]

- app/[locale]/(main)/chat/page.client.tsx
- app/[locale]/(main)/logs/live-log.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/chat-list.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/chat-panel.tsx
- app/[locale]/(main)/servers/[id]/console/console-input.tsx
- components/messages/chat-input.tsx
- Add consistent padding to ChatInput components across different pages
- Remove redundant padding from ChatInput form to avoid double padding
- Improve chat panel styling with rounded corners and border
- Set max height for chat list to prevent overflow
> style(ui): adjust padding and styling for chat components

- app/[locale]/(main)/servers/[id]/(dashboard)/chat-panel.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/init-server-button.tsx
- components/messages/message-card.tsx
The chat panel was extending beyond the viewport on smaller screens. Added max-width constraint to ensure it stays within bounds while maintaining a minimum width of 350px.
> fix(chat-panel): adjust chat panel width to prevent overflow

- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
The PauseServerButton was moved after ShutdownServerButton to maintain consistent ordering of destructive actions. This improves the UI's logical flow where more severe actions appear later in the sequence.
> fix(servers): reorder server action buttons for better logical flow

- app/[locale]/(main)/navbar-link.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/mismatch-panel.tsx
- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
- components/common/error-message.tsx
- components/common/error-screen.tsx
- components/common/report-error.dialog.tsx
- components/common/report-error.form.tsx
- components/server/cpu-progress.tsx
- components/server/server-card.tsx
- lib/error.ts
- query/server.ts
Add support for showing gamemode information when available, displayed after mode separated by a slash. This provides more detailed game mode information to users.
> feat(server-card): display gamemode alongside mode in server card

- app/[locale]/(main)/servers/[id]/(dashboard)/page.tsx
- app/[locale]/(main)/servers/[id]/layout.tsx
- components/common/color-text.tsx
- components/messages/message-card.tsx
- components/server/server-card.skeleton.tsx
- components/server/server-card.tsx
- Return null for empty color syntax cases in ColorText component to prevent rendering empty strings
- Add max-h-screen class to server dashboard layout for better responsive behavior
- Remove redundant text-base class from message card text styling
> fix: handle empty color syntax and adjust layout classes

- app/[locale]/(main)/translation/diff-table.tsx
- tailwind.config.ts
Remove redundant isEdit state and always show Textarea component to streamline the translation editing flow. This eliminates the toggle behavior and makes the interface more straightforward for users.
> refactor(translation): simplify diff table edit state handling

- app/[locale]/(main)/servers/[id]/setting/server-update-form.tsx
- types/request/UpdateServerRequest.ts
- types/response/Server.ts
- types/response/ServerDto.ts
Add optional discordChannelId field to server update schema and form to allow linking servers to Discord channels. This enables better Discord integration for server notifications and updates.
> feat(servers): add discord channel id field to server settings

- app/[locale]/(main)/logs/static-log.tsx
- components/log/log-card.tsx
- types/Log.ts
- Add `type` field to Log type definition
- Remove onClick filter functionality from LogCard and its usages
- Display images when log type is 11 instead of text content
> feat(logs): add image support for log type 11 and remove filter click

- middleware.ts
The matcher configuration in middleware.ts was updated to include 'webmanifest' in the exclusion list. This change improves the accuracy of route matching by ensuring webmanifest files are properly excluded from middleware processing.
> refactor(middleware): update matcher config for better exclusion

- app/[locale]/(main)/servers/[id]/(dashboard)/mismatch-panel.tsx
Improve layout consistency by using Tailwind's space-x utility instead of flex gap. Replace p tags with span for better semantic HTML.
> refactor(mismatch-panel): replace flex gap with space-x and p with span

- action/query.ts
- app/[locale]/(main)/admin/maps/[id]/loading.tsx
- app/[locale]/(main)/admin/maps/[id]/page.tsx
- app/[locale]/(main)/admin/schematics/[id]/loading.tsx
- app/[locale]/(main)/admin/schematics/[id]/page.tsx
- app/[locale]/(main)/maps/[id]/loading.tsx
- app/[locale]/(main)/maps/[id]/page.tsx
- components/button/copy.button.tsx
- components/map/map-detail-card.tsx
- components/map/map-preview-card.tsx
- components/map/upload-map-preview-card.tsx
- components/schematic/upload-schematic-preview-card.tsx
- remove loading.tsx files and use Suspense with skeleton directly
- disable prefetch for internal links to reduce unnecessary requests
- move cached query functions to centralized action/query.ts
- simplify map-detail-card by moving data fetching to server component
- remove redundant toast notification in copy button
> refactor: optimize data fetching and loading in map/schematic pages

- app/[locale]/(main)/translation-path-icon.tsx
Add NaN check before passing value to NotificationNumber to prevent potential display issues when the sum is not a number.
> fix: handle NaN case in translation path icon value

- components/common/json-display.tsx
The initial show state was changed from 0 to 50 to display more items by default. The show-more button was moved outside the nested div for better UI structure.
> fix(json-display): adjust initial show state and move show-more button

- app/[locale]/(main)/servers/[id]/(dashboard)/usage-panel.tsx
- components/server/cpu-progress.tsx
The CPU usage calculation was incorrectly rounding before multiplication, leading to inaccurate display. Also fixed the progress component to use the calculated value instead of the raw prop.
> fix(usage-panel): correct cpu usage calculation and display

- components/server/server-card.tsx
Improve layout by grouping official and version badges in a flex container to ensure consistent spacing between them
> refactor(server-card): wrap badges in flex container for better spacing

- app/[locale]/(main)/servers/[id]/(dashboard)/usage-panel.tsx
- app/[locale]/(main)/servers/[id]/stats/page.tsx
- components/metric/ram-usage-chart.tsx
- types/response/ServerDto.ts
- types/response/ServerStats.ts
- Add jvmRamUsage field to ServerDto and ServerStats types
- Update usage panel to display both server and native RAM usage
- Modify ram usage chart to show separate server and native RAM usage
- Add new jvm-ram chart to stats page
- Create LineChartWrapper component for consistent chart styling
> feat(server-stats): add jvm ram usage tracking and visualization

- LICENSE
- analyze/nodejs.html
- app/[locale]/(main)/servers/[id]/workflows/node-list-panel.tsx
- app/[locale]/(main)/servers/[id]/workflows/properties-panel.tsx
- app/[locale]/(main)/servers/[id]/workflows/workflow-editor.tsx
- app/[locale]/(main)/servers/[id]/workflows/workflow-node-item.tsx
- app/[locale]/(main)/servers/[id]/workflows/workflow-node.tsx
- app/[locale]/(main)/servers/[id]/workflows/workflow.utils.ts
- components/map/map-detail-card.tsx
- components/schematic/schematic-detail-card.tsx
- components/search/name-tag-search.tsx
- types/response/WorkflowContext.ts
- Updated WorkflowItem, PropertiesPanel, and WorkflowEditorProvider to replace references to consumers with fields.
- Adjusted the logic in workflow validation to check for required fields instead of consumers.
- Modified utility functions to handle field updates instead of consumer updates.
- Updated the WorkflowNode and NodeItem components to reflect the new fields structure.
- Refactored the NameTagSearch component to use debounced input for search functionality.
- Changed the WorkflowNodeData schema to define fields instead of consumers.
> refactor: replace consumers with fields in workflow components

- app/[locale]/(main)/medium-navigation-items.tsx
Refactor icon imports to be more readable with proper line breaks and add size class to RabbitMQ icon for consistent styling
> style(icons): format icon imports and fix RabbitMQ icon size

- lib/utils.ts
Move console.warn outside the retry loop to avoid duplicate logging and only show aggregated errors when max retries are reached
> refactor(utils): move error logging outside retry loop in withRetry

- app/[locale]/(main)/servers/[id]/(dashboard)/usage-panel.tsx
- components/server/ban.button.tsx
The calculation was incorrectly multiplying by 10 instead of 10000 to get the percentage, resulting in inaccurate display of RAM usage percentages.
> fix(usage-panel): correct ram usage percentage calculation

- i18n/client.ts
- i18n/server.ts
Remove redundant try-catch blocks and consolidate error handling for translation requests. The fetch promise chain now handles errors consistently and logs failures with more context.
> refactor(i18n): simplify fetch error handling in translation requests

- app/[locale]/(main)/servers/[id]/(dashboard)/has-server-map.tsx
Ensure the component only renders the warning when not in loading state to avoid flickering UI
> fix(dashboard): prevent empty render during server map loading

- app/[locale]/(main)/servers/[id]/(dashboard)/usage-panel.tsx
The calculation for RAM usage percentage was incorrect due to missing unit conversion. Fixed the display format to properly show used RAM in bytes and total RAM in MB, and corrected the percentage calculation by applying proper unit conversions.
> fix(usage-panel): correct ram usage calculation and display
